name       : cppcodec
version    : 0.2
release    : 1
source     :
    - https://github.com/tplgy/cppcodec/archive/v0.2.tar.gz : 0edaea2a9d9709d456aa99a1c3e17812ed130f9ef2b5c2d152c230a5cbc5c482
license    : MIT
component  : programming.library
summary    : Header-only C++11 library to encode/decode various encoding formats
description: |
    Header-only C++11 library to encode/decode base64, base64url, base32, base32hex and hex (a.k.a. base16) as specified in RFC 4648, plus Crockford's base32.
patterns   :
    - /usr
setup      : |
    %cmake -DBUILD_TESTING:BOOL=OFF
build      : |
    %make
install    : |
    %make_install